const TOKEN_ENDPOINT_LIMIT = Number.isInteger(process.env.TOEKN_ENDPOINT_LIMIT)
  ? process.env.TOEKN_ENDPOINT_LIMIT
  : 200

const TOKEN_ENDPOINT_LIMIT_WINDOW = Number.isInteger(
  process.env.TOKEN_ENDPOINT_LIMIT_WINDOW,
)
  ? process.env.TOKEN_ENDPOINT_LIMIT_WINDOW
  : 3600

const IP_ENDPOINT_LIMIT = Number.isInteger(process.env.IP_ENDPOINT_LIMIT)
  ? process.env.IP_ENDPOINT_LIMIT
  : 100

const IP_ENDPOINT_LIMIT_WINDOW = Number.isInteger(
  process.env.IP_ENDPOINT_LIMIT_WINDOW,
)
  ? process.env.IP_ENDPOINT_LIMIT_WINDOW
  : 3600

const PREDIFINED_TOKEN = [
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiZW1haWwiOiJ1c2VyMUBleGFtcGxlLmNvbSIsInVzZXJJZCI6IjEiLCJyb2xlSWQiOiJhZG1pbiJ9.h-js_QimTojnYFiUSKCIVFaIX2OtHyCvT92eK8CM9nA',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyIiwiZW1haWwiOiJ1c2VyMkBleGFtcGxlLmNvbSIsInVzZXJJZCI6IjIiLCJyb2xlSWQiOiJ1c2VyIn0.oHqoW76iDeOAqstmmjO9_WFkJjXGkH6YTzpTwP117Wo',
]

//TODO read it from env variable
const SECRET_KEY =
  'MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCQPILi4kXwp5YlGsugXfiIDk9o jjD8EQrI7ABuQ6aNbvViMG/J67A5Q2O+KMvPNgA3THPtwmHLAGfbNuMikMBxCI7j KiYF2HPYYtwY6WhneOc/VpT4aJtdt4oey7S85uUxbAhVh5iW5DPHf4Ob7wZTDl90 PijNSPrCFOdNLolTnwIDAQAB'

module.exports = {
  TOKEN_ENDPOINT_LIMIT,
  TOKEN_ENDPOINT_LIMIT_WINDOW,
  IP_ENDPOINT_LIMIT,
  IP_ENDPOINT_LIMIT_WINDOW,
  PREDIFINED_TOKEN,
  SECRET_KEY,
}
